package com.navio.communityservice.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "groups", schema = "social")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Group {
    @Id @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @Column(nullable = false, length = 120, updatable = false)
    private String name;
    @Column(nullable = false, length = 140, unique = true, updatable = false)
    private String slug;
    @Column(nullable = false, columnDefinition = "text")
    private String description;
    @Column(length = 120)
    private String country;
    @Builder.Default @JdbcTypeCode(SqlTypes.ARRAY) @Column(nullable = false, columnDefinition = "text[]")
    private String[] places = new String[0];
    @Builder.Default @JdbcTypeCode(SqlTypes.ARRAY) @Column(nullable = false, columnDefinition = "text[]")
    private String[] tags = new String[0];
    @Column(nullable = false, updatable = false)
    private UUID createdByUserId;
    @Column(nullable = false)
    private boolean isOfficial;
    @Builder.Default @Column(nullable = false, length = 30)
    private String status = "active";
    @Column(nullable = false)
    private int memberCount;
    @Column(nullable = false)
    private int postCount;
    @Column(nullable = false)
    private int weeklyVisitorCount;
    @Column(nullable = false)
    private int weeklyContributionCount;
    // search_vector is generated by PostgreSQL and queried only in native SQL.

    @Column(nullable = false, updatable = false)
    private Instant createdAt;
    @Column(nullable = false)
    private Instant updatedAt;
    @PrePersist
    void onCreate() { createdAt = updatedAt = Instant.now(); }
    @PreUpdate
    void onUpdate() { updatedAt = Instant.now(); }
}
